workflows:
  android-release:
      name: CoCo Android Release
          max_build_duration: 60
              environment:
                    flutter: stable

                        scripts:
                              - flutter pub get
                                    - flutter build apk --release

                                        artifacts:
                                              - coco/build/app/outputs/flutter-apk/app-release.apk

                                                  working_directory: CoCo